{{- if .Values.manager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentinel-manager
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.manager.service.service_type }}
  ports:
    - port: {{ .Values.manager.containerPort }}
      targetPort: {{ .Values.manager.containerPort }}
  selector:
    sentinel: {{ .Release.Name }}-manager
  {{- end -}}
