---
{{if .Values.agent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-synapse-agent-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    synapse: agent
data:
{{ toYaml .Values.agent.environment_variable.data | indent 2  }}
{{- end}}
---
{{if .Values.manager.managerrule.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-synapse-manager-rules-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    synapse: manager
data:
{{ toYaml .Values.manager.managerrule.data | indent 2 }}
{{- end}}
---

{{if .Values.manager.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-synapse-manager-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.manager.environment_variable.data | indent 2  }}
{{- end}}
---
