{{- if .Values.manager.ingress.enabled -}}
{{- $fullName := .Release.Name -}}
{{- $servicePort := .Values.manager.containerPort -}}
{{- $ingressPath := .Values.manager.ingress.path -}}
{{- $ingressPathType := .Values.manager.ingress.pathType -}}
{{- $extraPaths := .Values.manager.ingress.extraPaths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-morpheus-manager
  namespace: {{ .Release.Namespace }}
  labels:
    morpheus: {{ .Release.Name }}-manager
{{- if .Values.manager.ingress.labels }}
{{ toYaml .Values.manager.ingress.labels | indent 4 }}
{{- end }}
  {{- if .Values.servmanagerer.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.manager.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.manager.ingress.ingressClassName }}
  ingressClassName: {{ .Values.manager.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.manager.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.manager.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.manager.ingress.hosts  }}
  {{- range .Values.manager.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $fullName }}-morpheus-manager
                port:
                  number: {{ $servicePort }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}-morpheus-manager
                port:
                  number: {{ $servicePort }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            pathType: {{ $ingressPathType }}
  {{- end -}}
{{- end }}
