---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-synapse-secret
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  db_server_password: {{ .Values.manager.secret_variable.data.db_server_password | b64enc | quote }}
