apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-agent
  namespace: synapseagent
spec:
  selector:
    matchLabels:
      synapse:  agent
  replicas: 1 
  template:
    metadata:
      labels:
        synapse: agent
    spec:
      serviceAccountName: synapse-controller
      containers:
        - name: synapse-agent
          image: green:32000/nexclipper-synapse-agent
          env:
            - name: S_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: manager
            - name: S_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: clusterid
            - name: S_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: token
