apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-agent
  namespace: morpheusagent
spec:
  selector:
    matchLabels:
      morpheus:  agent
  replicas: 1 
  template:
    metadata:
      labels:
        morpheus: agent
    spec:
      serviceAccountName: morpheus-controller
      containers:
        - name: morpheus-agent
          image: green:32000/morpheus-morpheus-agent
          env:
            - name: S_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: morpheus-configmap
                  key: manager
            - name: S_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: morpheus-configmap
                  key: clusterid
            - name: S_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: morpheus-configmap
                  key: token
