apiVersion: v1
kind: ServiceAccount
metadata: 
  name: morpheus-controller
  namespace: morpheusagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: morpheus-controller
  namespace: morpheusagent
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: morpheus-controller
subjects:
- kind: ServiceAccount
  name: morpheus-controller
  namespace: morpheusagent 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: morpheus-controller
