agent:
  enabled: true
  image: "jaehoon/synapse-agent:latest"
  environment_variable:
    data:
      manager: "" #http://<IP>:<PORT>
      clusterid: ""
      token: ""

manager:
  enabled: true
  service:
    service_type: "ClusterIP"
  image: "jaehoon/synapse-manager:latest"
  containerPort: 8099
  environment_variable:
    data:
      SYNAPSE_DB_HOST: "mysql.db.svc.cluster.local"
      SYNAPSE_DB_PORT: "3306"
      SYNAPSE_DB_SCHEME: "synapse"
      SYNAPSE_DB_EXPORT_PATH: "."
      SYNAPSE_DB_SERVER_USERNAME: "synapse"
      SYNAPSE_LOG_SEVERITY: "info"
      SYNAPSE_LOG_SYSTEM_EVENT: "false"
      SYNAPSE_LOG_VERBOSE: "true"
      SYNAPSE_LOG_VERBOSELEVEL: "9"
      SYNAPSE_LOG_FILENAME: "./synapse.log"
      SYNAPSE_LOG_MAXSIZE: "10"
      SYNAPSE_LOG_MAXAGE: "5"
      SYNAPSE_LOG_MAXBACKUPS: "10"
      SYNAPSE_LOG_COMPRESS: "false"
  secret_variable:
    data:
      db_server_password: "synapse"
  managerrule:
    enabled: false
    data:
     enigma.yml: |
       enigma:
         synapse.default.crypto:
           block-method: none
           block-size: 0
           block-key:
           cipher-mode: none
           cipher-salt: null
           padding: none
           strconv: plain
  ingress:
    enabled: false
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: nginx
    # Values can be templated
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    labels: {}
    path: /
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    # By default, Kubernetes uses an ingress controller named nginx if the ingress class name is not specified.
    # ingressClassName: ""
    hosts:
      - chart-example.local
    ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
    extraPaths: []
    # - path: /*
    #   backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    ## Or for k8s > 1.19
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service:
    #       name: ssl-redirect
    #       port:
    #         name: use-annotation
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

