apiVersion: v1
kind: Service
metadata:
  name: synapse-manager
  namespace: synapse 
spec:
  type: LoadBalancer
  ports:
    - port: 8099
      targetPort: 8099
  selector:
    synapse: manager 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-manager
  namespace: manager
spec:
  selector:
    matchLabels:
      synapse: manager
  replicas: 1 
  template:
    metadata:
      labels:
        synapse: manager
    spec:
      containers:
        - name: synapse-manager
          image: green:32000/synapse-manager:0.0.1
          ports:
            - containerPort: 8099
          env:
            - name: SYNAPSE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: db_host
            - name: SYNAPSE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: db_port
            - name: SYNAPSE_DB_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: db_scheme
            - name: SYNAPSE_DB_EXPORT_PATH
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: db_export_path
            - name: SYNAPSE_DB_SERVER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: db_server_username
            - name: SYNAPSE_DB_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-secret
                  key: db_server_password
            - name: SYNAPSE_LOG_SEVERITY
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_severity
            - name: SYNAPSE_LOG_SYSTEM_EVENT
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap            
                  key: log_system_event
            - name: SYNAPSE_LOG_VERBOSE
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap 
                  key: log_verbose
            - name: SYNAPSE_LOG_VERBOSELEVEL
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_verboselevel
            - name: SYNAPSE_LOG_FILENAME
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_filename
            - name: SYNAPSE_LOG_MAXSIZE
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_maxsize
            - name: SYNAPSE_LOG_MAXAGE
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_maxage
            - name: SYNAPSE_LOG_MAXBACKUPS
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_maxbackups
            - name: SYNAPSE_LOG_COMPRESS
              valueFrom:
                configMapKeyRef:
                  name: synapse-configmap
                  key: log_compress
