apiVersion: v1
kind: Namespace
metadata:
  name: synapse
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-configmap
  namespace: synapse
data:
  db_host: ""
  db_port: "3306"
  db_scheme: "synapse"
  db_export_path: "."
  db_server_username: "synapse"
  log_severity: "info"
  log_system_event: "false"
  log_verbose: "true"
  log_verboselevel: "9"
  log_filename: "./synapse.log"
  log_maxsize: "10"
  log_maxage: "5"
  log_maxbackups: "10"
  log_compress: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: synapse-secret
  namespace: synapse
type: Opaque
data:
  db_server_password: ""
